De-linting for Arm_Control_System Branch
WisconsinRobotics/WRover_Software pull request #22
Opened 2022-04-28 23:37 UTC by Tzanccc

De-linting the arm control system to pass clang tests. Refactoring wr_control_drive_arm as well as removing unused code.

2022-04-29 00:44 UTC, bennowotny requested changes
Some old, extraneous code to removed before merging.

2022-04-29 00:44 UTC, bennowotny commented on src/wr_control_drive_arm/src/ArmControlSystem.cpp
> +// ArmMotor *motors[numMotors];
If not used, can be removed.

2022-04-29 00:44 UTC, bennowotny commented on src/wr_control_drive_arm/src/ArmControlSystem.cpp
> +  // TODO: fix
Fixed, so can be removed.

2022-04-29 00:44 UTC, bennowotny commented on src/wr_control_drive_arm/src/ArmControlSystem.cpp
> +  // TODO: fix
Fixed, so can be removed.

2022-04-29 00:53 UTC, Tzanccc reviewed
Old code removed

2022-05-01 21:22 UTC, bennowotny approved these changes
Ready to go, will be merged.

2022-05-01 21:22 UTC, merged