55 document all ros packages pt. 1
WisconsinRobotics/WRover_Software pull request #66
Opened 2023-07-15 23:45 UTC by bennowotny

Closes #55

2023-07-18 02:13 UTC, srao32 commented
For some reason, the collaboration diagrams don't show up for the modules under wrover_control_drive_science.

2023-07-18 02:52 UTC, srao32 requested changes

2023-07-18 02:52 UTC, srao32 commented on src/wr_control_drive_science/README.md
> +## Hardware Description (move me to wr_control_drive_science)
```suggestion
## Hardware Description
```

2023-07-21 01:42 UTC, bennowotny commented on src/wroboarm_23/README.md
> +
Addressed in d9035cd.

2023-07-21 01:42 UTC, bennowotny commented on src/wroboarm_23/README.md
> +The `demo.launch` file is autogenerated, and `demo_test.launch` is a slightly modified version of that file made to launch correctly across the WRover system.
Addressed in d9035cd.

2023-07-21 02:04 UTC, srao32 approved these changes

2023-07-21 02:06 UTC, bennowotny commented
This PR will not merge.  When the story is really complete, we will re-review and merge then.

2023-07-21 02:06 UTC, closed without merging